CREATE TABLE Cargo
(
    id             INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name           VARCHAR(255) NOT NULL,
    content        TEXT         NOT NULL,
    departure_city VARCHAR(255) NOT NULL,
    departure_date DATE         NOT NULL,
    arrival_city   VARCHAR(255) NOT NULL,
    arrival_date   DATE         NOT NULL
);