spring:
  datasource:
    url: jdbc:postgresql://cargo-transportation-db:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true